version: '3.4'

services:
  ext.net.examples:
    image: ${DOCKER_REGISTRY-}extnetexamples
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"
